name: ramadan_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  auto_route: ^11.1.0
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  get_storage: ^2.1.1
  google_fonts: 7.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  permission_handler: ^12.0.1
  retrofit: ^4.9.2
  shimmer: ^3.0.0
  smooth_compass: ^2.0.17
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.3
  retrofit_generator: ^10.2.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/
    - assets/images/
    - assets/images/categories/
    - assets/images/titles/
    - assets/images/ramadan_time/
    - assets/images/qiable_finder/
    - assets/images/prayer/
    - assets/icons/
    - assets/images/onboarding/
    - assets/images/error/
    - assets/images/permission/
    - assets/json/
